# pytmux 설치(Windows) — install.sh 의 PowerShell 대응판.
# 세 가지를 자동화한다:
#   1) 의존성 설치(pip install -r requirements.txt)
#   2) 어디서든 `pytmux` 로 실행되도록 PATH 상의 디렉터리에 얇은 래퍼(pytmux.cmd) 생성
#   3) `python` 명령 shim — minimal PATH 셸에서도 `python pytmux.py` 가 되도록
#      ~/.local/bin 에 python/python.cmd 생성(자세한 배경: docs/ENV_SETUP_WINDOWS.md)
# 래퍼는 이 저장소의 pytmux.py 절대경로를 가리키므로 저장소를 옮기지 않는 한 그대로 동작한다.
#
# 사용법(PowerShell):
#   .\install.ps1                   # 의존성 + 런처 + python shim 전부
#   .\install.ps1 -Dir C:\bin       # 런처를 다른 디렉터리에 설치
#   .\install.ps1 -Bin pytmux2      # 다른 이름으로 설치
#   .\install.ps1 -ShimDir D:\bin   # python shim 위치 지정(기본 ~/.local/bin)
#   .\install.ps1 -SkipDeps         # 의존성 설치 건너뜀
#   .\install.ps1 -SkipShim         # python shim 생성 건너뜀
#
# 제거: .\uninstall.ps1 (같은 인자 규칙)
[CmdletBinding()]
param(
    [string]$Dir = (Join-Path $env:LOCALAPPDATA 'pytmux\bin'),
    [string]$Bin = 'pytmux',
    [string]$ShimDir = (Join-Path $HOME '.local\bin'),
    [switch]$SkipDeps,
    [switch]$SkipShim
)
$ErrorActionPreference = 'Stop'

# 이 스크립트(=저장소 루트)의 절대경로.
$Repo  = $PSScriptRoot
$Entry = Join-Path $Repo 'pytmux.py'
$Reqs  = Join-Path $Repo 'requirements.txt'
$Target = Join-Path $Dir ("{0}.cmd" -f $Bin)

# 생성 파일 식별 마커 — uninstall.ps1 이 이 문자열로 "자기가 만든 것만" 골라 지운다.
# 두 스크립트가 같은 리터럴을 써야 하므로 한쪽을 바꾸면 다른 쪽도 맞출 것.
$ShimMarker = 'Generated by pytmux install.ps1'

if (-not (Test-Path -LiteralPath $Entry)) {
    Write-Error "오류: 진입점을 찾을 수 없습니다: $Entry"
    exit 1
}

# python 런처 탐색(python 우선, 없으면 py 런처).
$Py = 'python'
if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
    if (Get-Command py -ErrorAction SilentlyContinue) {
        $Py = 'py'
    } else {
        Write-Warning "python(또는 py)을 PATH 에서 찾지 못했습니다. 설치는 계속하지만 실행 시 필요합니다."
        $Py = $null
    }
}

# --- 1) 의존성 설치 ---
if (-not $SkipDeps) {
    if ($Py -and (Test-Path -LiteralPath $Reqs)) {
        Write-Host "의존성 설치: $Py -m pip install -r requirements.txt"
        & $Py -m pip install -r $Reqs
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "의존성 설치 실패(코드 $LASTEXITCODE). 수동 실행: $Py -m pip install -r `"$Reqs`""
        }
    } elseif (-not $Py) {
        Write-Warning "python/py 가 없어 의존성 설치를 건너뜁니다."
    }
}

# --- 2) pytmux 런처 ---
New-Item -ItemType Directory -Force -Path $Dir | Out-Null

# pytmux.cmd 래퍼 — 진입점으로 전달. %* 로 모든 인자 전달, @ 로 에코 억제.
# $Py 가 없으면(둘 다 못 찾음) 런타임에 python 을 기대.
$Launcher = if ($Py) { $Py } else { 'python' }
$wrapper = @"
@echo off
rem $ShimMarker - launcher. entry: $Entry
$Launcher "$Entry" %*
"@
Set-Content -LiteralPath $Target -Value $wrapper -Encoding ASCII
Write-Host "런처 설치: $Target -> $Entry"

# Dir 이 PATH 에 없으면 안내.
$paths = ($env:PATH -split ';') | ForEach-Object { $_.TrimEnd('\') }
if ($paths -notcontains $Dir.TrimEnd('\')) {
    Write-Host "주의: $Dir 가 PATH 에 없습니다. 사용자 PATH 에 추가하려면:"
    Write-Host "  setx PATH `"`$env:PATH;$Dir`"   (새 터미널부터 적용)"
}

# --- 3) python 명령 shim ---
# minimal PATH 셸(SSH/로그인)에서는 Store Python 의 WindowsApps 별칭이 PATH 에서
# 빠져 `python` 이 안 잡힌다. 실제 동작하는 인터프리터로 포워딩하는 shim 을
# ~/.local/bin(모든 셸 PATH 에 있음)에 만든다. 배경: docs/ENV_SETUP_WINDOWS.md
if (-not $SkipShim) {
    # 위에서 찾은 $Py 를 그대로 써서 *실제 동작하는* 인터프리터 절대경로를 얻는다
    # (py 런처/별칭은 sys.executable 로만 실 경로가 드러나므로 -c 로 질의).
    $realExe = if ($Py) { (& $Py -c "import sys; print(sys.executable)").Trim() } else { $null }

    if ($realExe -and (Test-Path -LiteralPath $realExe)) {
        New-Item -ItemType Directory -Force -Path $ShimDir | Out-Null

        # cmd/PowerShell 용 (.cmd)
        $cmdShim = Join-Path $ShimDir 'python.cmd'
        $cmdBody = "@echo off`r`nrem $ShimMarker - python command shim -> $realExe`r`n`"$realExe`" %*`r`n"
        [IO.File]::WriteAllText($cmdShim, $cmdBody, (New-Object System.Text.ASCIIEncoding))

        # git-bash/msys2 용 (확장자 없음, LF, BOM 없음). 윈도 경로를 /c/... 형태로 변환.
        $unix = '/' + $realExe.Substring(0,1).ToLower() + ($realExe.Substring(2) -replace '\\','/')
        $shShim = Join-Path $ShimDir 'python'
        $shBody = "#!/usr/bin/env bash`n# $ShimMarker - python command shim`nexec `"$unix`" `"`$@`"`n"
        [IO.File]::WriteAllText($shShim, $shBody, (New-Object System.Text.UTF8Encoding($false)))

        Write-Host "python shim 생성: $cmdShim / $shShim -> $realExe"

        if ($paths -notcontains $ShimDir.TrimEnd('\')) {
            Write-Host "주의: $ShimDir 가 PATH 에 없습니다. shim 이 잡히도록 PATH 에 추가하세요."
        }
    } else {
        Write-Warning "동작하는 python 실행 파일을 찾지 못해 shim 을 건너뜁니다(-SkipShim 으로 끌 수 있음)."
    }
}

Write-Host "설치 완료."
